language: go
services:
  - docker
go:
  - 1.13.x
install:
  - go get -u github.com/vbatts/git-validation
script:
  - git-validation -run DCO,short-subject
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - go vet $(go list ./... | grep -v vendor)
  - make install
  - make test
  - make docs
  - cd component/examples/golang && make verify
