language: go
services:
  - docker
go:
  - 1.13.x
script:
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - go vet $(go list ./... | grep -v vendor)
  - make install
  - make test
  - make docs
