current: source
configurations:
- context: source
  token: ""
  endpoint: localhost:9920
  secure: false
  kubeconfig: ""
- context: target
  token: ""
  endpoint: localhost:9921
  secure: false
  kubeconfig: ""
